### PR TITLE
Visual changes made

### PR DESCRIPTION
**Pull request by vm1000**

### CODE REVIEW

**Comment by ghost** [comment]
App crashes
Crash

Stack trace
```
2019-05-02 11:34:10.696876+0300 simple-weather[55967:134997] *** Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<simple_weather.ViewController 0x7f8cccc06870> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key backgroundColor.'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000108cb76fb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x00000001070d9ac5 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000108cb7269 -[NSException raise] + 9
	3   Foundation                          0x0000000106b4e562 -[NSObject(NSKeyValueCoding) setValue:forKey:] + 289
	4   UIKitCore                           0x0000000111caa2d2 -[UIViewController setValue:forKey:] + 87
	5   UIKitCore                           0x0000000111f378fd -[UIRuntimeOutletConnection connect] + 109
	6   CoreFoundation                      0x0000000108ca3d41 -[NSArray makeObjectsPerformSelector:] + 305
	7   UIKitCore                           0x0000000111f34643 -[UINib instantiateWithOwner:options:] + 1810
	8   UIKitCore                           0x0000000111cb13af -[UIViewController _loadViewFromNibNamed:bundle:] + 382
	9   UIKitCore                           0x0000000111cb1d39 -[UIViewController loadView] + 177
	10  UIKitCore                           0x0000000111cb2048 -[UIViewController loadViewIfRequired] + 172
	11  UIKitCore                           0x0000000111cb2868 -[UIViewController view] + 27
	12  UIKitCore                           0x00000001122eac33 -[UIWindow addRootViewControllerViewIfPossible] + 122
	13  UIKitCore                           0x00000001122eb327 -[UIWindow _setHidden:forced:] + 289
	14  UIKitCore                           0x00000001122fdf86 -[UIWindow makeKeyAndVisible] + 42
	15  UIKitCore                           0x00000001122adf1c -[UIApplication _callInitializationDelegatesForMainScene:transitionContext:] + 4555
	16  UIKitCore                           0x00000001122b30c6 -[UIApplication _runWithMainScene:transitionContext:completion:] + 1617
	17  UIKitCore                           0x0000000111af86d6 __111-[__UICanvasLifecycleMonitor_Compatability _scheduleFirstCommitForScene:transition:firstActivation:completion:]_block_invoke + 904
	18  UIKitCore                           0x0000000111b00fce +[_UICanvas _enqueuePostSettingUpdateTransactionBlock:] + 153
	19  UIKitCore                           0x0000000111af82ec -[__UICanvasLifecycleMonitor_Compatability _scheduleFirstCommitForScene:transition:firstActivation:completion:] + 236
	20  UIKitCore                           0x0000000111af8c48 -[__UICanvasLifecycleMonitor_Compatability activateEventsOnly:withContext:completion:] + 1091
	21  UIKitCore                           0x0000000111af6fba __82-[_UIApplicationCanvas _transitionLifecycleStateWithTransitionContext:completion:]_block_invoke + 782
	22  UIKitCore                           0x0000000111af6c71 -[_UIApplicationCanvas _transitionLifecycleStateWithTransitionContext:completion:] + 433
	23  UIKitCore                           0x0000000111afb9b6 __125-[_UICanvasLifecycleSettingsDiffAction performActionsForCanvas:withUpdatedScene:settingsDiff:fromSettings:transitionContext:]_block_invoke + 576
	24  UIKitCore                           0x0000000111afc610 _performActionsWithDelayForTransitionContext + 100
	25  UIKitCore                           0x0000000111afb71d -[_UICanvasLifecycleSettingsDiffAction performActionsForCanvas:withUpdatedScene:settingsDiff:fromSettings:transitionContext:] + 223
	26  UIKitCore                           0x0000000111b006d0 -[_UICanvas scene:didUpdateWithDiff:transitionContext:completion:] + 392
	27  UIKitCore                           0x00000001122b19a8 -[UIApplication workspace:didCreateScene:withTransitionContext:completion:] + 514
	28  UIKitCore                           0x0000000111e68dfa -[UIApplicationSceneClientAgent scene:didInitializeWithEvent:completion:] + 361
	29  FrontBoardServices                  0x000000011506e125 -[FBSSceneImpl _didCreateWithTransitionContext:completion:] + 448
	30  FrontBoardServices                  0x0000000115077ed6 __56-[FBSWorkspace client:handleCreateScene:withCompletion:]_block_invoke_2 + 283
	31  FrontBoardServices                  0x0000000115077700 __40-[FBSWorkspace _performDelegateCallOut:]_block_invoke + 53
	32  libdispatch.dylib                   0x000000010a03adb5 _dispatch_client_callout + 8
	33  libdispatch.dylib                   0x000000010a03e2ba _dispatch_block_invoke_direct + 300
	34  FrontBoardServices                  0x00000001150a9146 __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 30
	35  FrontBoardServices                  0x00000001150a8dfe -[FBSSerialQueue _performNext] + 451
	36  FrontBoardServices                  0x00000001150a9393 -[FBSSerialQueue _performNextFromRunLoopSource] + 42
	37  CoreFoundation                      0x0000000108c1ebe1 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	38  CoreFoundation                      0x0000000108c1e463 __CFRunLoopDoSources0 + 243
	39  CoreFoundation                      0x0000000108c18b1f __CFRunLoopRun + 1231
	40  CoreFoundation                      0x0000000108c18302 CFRunLoopRunSpecific + 626
	41  GraphicsServices                    0x000000010bbc02fe GSEventRunModal + 65
	42  UIKitCore                           0x00000001122b4ba2 UIApplicationMain + 140
	43  simple-weather                      0x00000001067dc48b main + 75
	44  libdyld.dylib                       0x000000010a0af541 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

**Comment by ghost** [comment]
Other things to improve:
Duplicate, why set array with 40 items, then filter those and reset same array with 7 items. Remove initial set
Source code

**Comment by ghost** [comment]
In `Info.plist` there is redundant permission request messages
Permission
It's either **first**, **second** or **both**. In our case only `Privacy - Location When In Use Usage Description` is enough and you'll have to replace `locationManager.requestAlwaysAuthorization()` to `locationManager.requestWhenInUseAuthorization()`

**Comment by ghost** [comment]
You are using `manager.location?.coordinate` to gather coordinates in delegate method of `CLLocationDelegate` but if has dedicated parameter for it `didUpdateLocations locations: [CLLocation]` you have to use it `locations.last?.coordinates`

CLLocationDelegate

**Review by ghost — CHANGES_REQUESTED** [review]
Address remarks

**Comment by vm1000** [comment]
Thanks for review! 
Changed that was requested.

**Review by ghost — CHANGES_REQUESTED** [review]
Couple of additional things to change to finalize assignment.

1. `locationManager.desiredAccuracy = kCLLocationAccuracyThreeKilometers` does not what I initially thought - it does not ask for location after some distance, but simply allows larger error margin (which could result in incorrect city name), therefore, we will remove it, that way `CLLocationManager` will use default it's value `kCLLocationAccuracyBest`.
2. Instead we will specify `locationManager.distanceFilter = 1000` which would ask for new location after every kilometer, (currently even if coordinate is static, it spams requests to APIs, that makes `TableView` appear to lag, when scrolling, because it reloads data every second);
3. Improved UX by giving color to `TableView` (tableViewBackgroundGray that you have in cells) and `View` of ViewController (blue that you have at currentWeather view).
4. And last, but not least, clear project tree, there are some empty folders `Extensions` and unnecessary folders and files `Extras`

**Review by ghost — APPROVED** [review]
🚀

**Pull request merged**
